import Head from 'next/head';
import { Inter } from 'next/font/google';
import Hero from '@/components/hero/hero.component';
import DownloadApp from '@/components/download-app/download-app.component';
import MoreThanFood from '@/components/more-than-food/more-than-food.component';
import HowToFozo from '@/components/how-to-fozo/how-to-fozo.component';
import ReadyToBecomeAHero from '@/components/ready-to-become-hero/ready-to-become-hero.component';

const interFont = Inter({
  variable: '--font-inter',
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Fozo</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='min-h-screen w-screen max-w-full relative'>
        <div className='pb-footer h-full w-full'>
          <Hero />
          <DownloadApp />
          <MoreThanFood />
          <HowToFozo />
          <ReadyToBecomeAHero />
        </div>
        <div className='h-footer w-full absolute bottom-0 left-0'></div>
      </div>
    </>
  );
}
